# https://cloud.google.com/appengine/docs/flexible/reference/app-yaml?tab=node.js#top
runtime: nodejs18

handlers:
  - url: /static/js/(.*)
    static_files: dist/static/js/\1
    upload: dist/static/js/(.*)
  - url: /static/css/(.*)
    static_files: dist/static/css/\1
    upload: dist/static/css/(.*)
  - url: /static/media/(.*)
    static_files: dist/static/media/\1
    upload: dist/static/media/(.*)
  - url: /(.*\.(json|ico))$
    static_files: dist/\1
    upload: dist/.*\.(json|ico)$
  - url: /
    static_files: dist/index.html
    upload: dist/index.html
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
