# https://cloud.google.com/appengine/docs/flexible/reference/app-yaml?tab=node.js#top
runtime: nodejs18

handlers:
  - url: /static/js/(.*)
    static_files: dist/assets/js/\1
    upload: dist/assets/js/(.*)

  - url: /(.*\.css)
    static_files: dist/\1
    mime_type: text/css
    upload: dist/.*\.css

  - url: /static/media/(.*)
    static_files: dist/assets/media/\1
    upload: dist/assets/media/(.*)
 
  - url: /(.*\.(json|ico))$
    static_files: dist/\1
    upload: dist/.*\.(json|ico)$

  - url: /
    static_files: dist/index.html
    upload: dist/index.html
    
  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
