# https://cloud.google.com/appengine/docs/flexible/reference/app-yaml?tab=node.js#top
runtime: nodejs18

handlers:
  - url: /static/js/
    static_dir: dist/assets/js/

  - url: /assets/css/
    static_dir: dist/assets/css

  - url: /static/media/
    static_dir: dist/assets/media
 
  - url: /(.*\.(json|ico))$
    static_files: dist/\1
    upload: dist/.*\.(json|ico)$

  - url: /
    static_files: dist/index.html
    upload: dist/index.html

  - url: /.*
    static_files: dist/index.html
    upload: dist/index.html
